---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: ashutosh
  become: false
  tasks:
  
    - name: Pull Docker Image
      docker_image:
        name: "ashutoshj/calc"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker rm -f calc && docker run -it -d --name calc ashutoshj/calc
    